# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: yagnikm/wisecow:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build-and-push

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Authenticate to Google Cloud
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Add GPG key for Google Cloud SDK
#         run: |
#           curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

#       - name: Install Google Cloud SDK and gke-gcloud-auth-plugin
#         run: |
#           REPO_URL="https://packages.cloud.google.com/apt"
#           echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
#           sudo apt-get update -y
#           sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin

#       - name: Configure kubectl
#         run: |
#           gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --region ${{ secrets.GKE_ZONE }}

#       - name: Set up kubectl
#         uses: azure/setup-kubectl@v1
#         with:
#           version: 'latest'

#       - name: Deploy to GKE
#         run: |
#           kubectl apply -f deployment.yaml
#           kubectl apply -f service.yaml
